### ISSUE TITLE
GUI people are lazy

### ISSUE THREAD

**Issue by Arctican4Real** [ineed-cmyk/SANN#2]
Bro I'm telling you these GUI people take too long to make a text box. Back end people are the real top g ong fr fr. Please fire the front end people amen.

**Comment by notausernaem** [comment]
guys me no have phone

**Comment by notausernaem** [comment]
are you guys up

**Comment by notausernaem** [comment]
u funushed the drop down menu thing

**Comment by notausernaem** [comment]
and also main page except for the colors im doing them rn

**Comment by Arctican4Real** [comment]
We did gud
